### ISSUE TITLE
Melting Obsidian

### ISSUE THREAD

**Issue by shinjilumiere** [Zkaface/TAIGA#64]
Currently Obsidian melts into Lava, is this intended? I'm having trouble getting Molten Obsidian due to the recipe addition.

![2016-11-18_12 35 24](https://cloud.githubusercontent.com/assets/5378903/20418748/a8f8524a-ad8b-11e6-9b86-77fd05b8cf13.png)

(Currently using TAIGA 1.1.4)

**Comment by IdleGandalf** [comment]
I don't know what purpose that recipe has, but at least it's gone in our current 1.2 development branch. Maybe that was just a mistake by Zkaface, don't know for sure until he comes back online tho. 

As we probably won't release another bugfix version before 1.2, I recommend turning the obsidian alloy option in the tinkers construct config on, so that you can create obsidian from water and lava in the smeltery.

**Comment by Zkaface** [comment]
@shinjilumiere This is a big issue I've seen by myself! In 1.2 obsidian will melt to obsidian again.

**Comment by shinjilumiere** [comment]
I see.
Commenting out line 105 of TAIGA/src/main/java/com/sosnitzka/taiga/Fluids.java might help.
Thank you for the response.

**Comment by IdleGandalf** [comment]
1.2 just hit CurseForge, this should be fixed now.
